[workspace]
members = [
  "crates/jd_api",
  "crates/jd_app",
  "crates/jd_core",
  "crates/jd_domain",
  "crates/jd_infra",
  "crates/jd_utils"
]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # For experimental dev.
