[workspace]
members = [
  "crates/asr_api",
  "crates/asr_app",
  "crates/asr_core",
  "crates/asr_domain",
  "crates/asr_infra",
  "crates/asr_utils"
]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # For experimental dev.
