version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - db_rust_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=400'
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    networks:
      - rust_server
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password!2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    restart: always
    volumes:
      - sql_data:/var/opt/mssql

networks:
  rust_server:
volumes:
  db_rust_data:
  sql_data:
