[package]
name = "jd_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
modql.workspace = true
sea-query.workspace = true

serde = { version = "1.0.204", features = ["derive"] }
sqlx = { version = "0.7.4", features = ["postgres"] }
