[package]
name = "jd_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
modql = { version = "0.3.10", features = ["with-sea-query"] }
sea-query = "0.30.7"
serde = { version = "1.0.204", features = ["derive"] }
sqlx = { version = "0.7.4", features = ["postgres"] }
