[package]
name = "asr_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio-rustls"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }
tiberius = { version = "0.12", features = ["chrono", "tokio", "tds73"] }
bb8 = "0.8"
bb8-tiberius = "0.14"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat"] }
futures-util = "0.3"

# Members
asr_core = { path = "../asr_core" }
asr_domain = { path = "../asr_domain" }
sea-query = "0.30.7"
modql = { version = "0.3.10", features = ["with-sea-query"] }
sea-query-binder = { version = "0.5.0", features = ["sqlx-postgres"] }
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["derive"] }
serde_with = "3.9.0"
